# Generated by Django 3.1 on 2020-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('written_on', models.DateTimeField(auto_now_add=True)),
                ('place', models.CharField(max_length=50)),
                ('feature_image', models.FileField(default='None', upload_to='uploads/')),
                ('category', models.CharField(choices=[('BR', 'Breaking'), ('IN', 'International'), ('NT', 'National'), ('ST', 'State'), ('DT', 'District'), ('LC', 'Local'), ('CL', 'Classifieds'), ('TC', 'Technology'), ('SP', 'Sports')], default='BR', max_length=10)),
                ('article', models.CharField(max_length=500)),
            ],
        ),
    ]
